name: Publish to Npm
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-2019 # the build errored out on windows-2022 (currently windows-latest)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build the C++ solution
        run: |
          msbuild ./AutomationTtsEngine.sln -v:diag -property:Configuration=Release

      - name: Inspect build outputs
        run: |
          ls 
          cd Release/
          ls

      - uses: actions/setup-node@v3 # Appears to be needed solely to avoid auth issues with npm publish
        with:
          node-version: 18

      - name: Publish to Npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}